### ISSUE TITLE
Fix load stress issue

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-data-hub#768]
We had an last evening that caused odd failures.  An example:

22:30:47 SEND of 0bdaca77-30b2-4d31-9985-ffbf207c8cd9 starts
22:31:22 logs show that the job partly worked - the request to retry was logged in the logs.  And the request to retry was updated in the Task table.
<sometime soon after> :	that SendFunction must have failed completely (???), because the Action history is never logged. (ActionHistory is outside of the main transaction now)
22:33:31 **both** the retry and the original run appear to start again at the same time.  (!)

Proposed workaround:
- add more logging so I can get more visibility into what’s going on
- implement batching for Redox, which effectively gives us good control over when Sends occur, and lets us spread them out.  Originally, I was thinking we could use randomization to spread out the Sends to Redox over some time period, but a no-code solution is much cleaner.
- add a capability to the requeue function to be able to figure out which records have been sent, in cases like last night, where there were partial failures.

**Comment by jimduff-usds** [comment]
There are two problems I'm seeing at the moment:

1.   We continue to see timeout issues when the system is experience a heavy load.    It shows up as an exception that looks like this:

> Result: Send function unrecoverable exception for event: report&SEND&2b68e551-e05d-48c2-ab01-43cd0172590a
> Exception: Error getting connection from data source HikariDataSource (HikariPool-4)
> Stack: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-4)
>        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
>        at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:612)
>        at gov.cdc.prime.router.azure.DatabaseAccess.transact(DatabaseAccess.kt:58)
>        at gov.cdc.prime.router.azure.WorkflowEngine.handleReportEvent(WorkflowEngine.kt:122)
>        at gov.cdc.prime.router.azure.SendFunction.run(SendFunction.kt:52)
> Suppressed: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-4)
>                                   Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out a\
> fter 30000ms.
>                                                      at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
>                                                         ... 28 more
> Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
>        at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
>        ... 28 more
This exception sometimes (always?) appears twice - it is both caught by our code and causes a retry, and it is NOT caught by our code, and that causes Azure to do a retry.  The second retry is bad, because it doesn't know about any partially transmitted data.  Its possible the non-caught exception is coming the connection pool thread, running separate from the Function thread?

2.  The very strange 'lateinit' exception.  It looks like this:

Result: Send function unrecoverable exception for event: report&SEND&71228d71-c8ac-4d1a-a61a-0d6beec4f945&2021-04-06T23:14:08.057729Z

> Exception: lateinit property nextEvent has not been initialized
> Stack: kotlin.UninitializedPropertyAccessException: lateinit property nextEvent has not been initialized
> 	at gov.cdc.prime.router.azure.WorkflowEngine.handleReportEvent(WorkflowEngine.kt:148)
> 	at gov.cdc.prime.router.azure.SendFunction.run(SendFunction.kt:52)

I have added logging to get a clearer picture of why this is occurring.  My working theory is that the sanity check on line 136 is failing - there was no logging there earlier.

**Comment by jimduff-usds** [comment]
On the second issue:  

While messing around with heavy load tests locally,I got that weird ‘lateinit’ error.
Its some weirdness where the threads get out of order:  First, one thread marks the job as NextAction = NONE, that is, no more work to do.   Then another thread that started earlier  comes along and tries to do work on that same job, and gets confused.   Right now it throws an exception.  The fix is for that thread to simply stop and die.

**Comment by jimduff-usds** [comment]
Regarding the first issue, @ronaldheft-usds has made further adjustments to the number of database connections and the number of queue items being processed at one time.

The idea is to keep the total # of worker threads (**across all worker azure functions**) less than the number of database pool threads.  While we cannot currently control the number of simultaneous ReportFunction calls, we can control the numbers for BatchFunction and SendFunction.

As of this writing, using Ron's latest settings, locally I'm able to make 25 simultaneous submissions to the ReportFunction, and have them flow to completion, with no exceptions.  And this is sending HL7 singletons, which is our transport that is most punishing to the system.

**Comment by jimduff-usds** [comment]
Closing this - we have gotten both these issues under control
